# -*- coding: utf-8 -*-
"""PES, Bill extraction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ocx-4i2sgsT0-mWSxlV99ytkWqbny2mX
"""

!pip install pytesseract
!apt-get install tesseract-ocr

"""### ***`TEXT EXTRACTION`***"""

import pytesseract
from PIL import Image
import os

# Set the path to the Tesseract executable
pytesseract.pytesseract.tesseract_cmd = '/usr/bin/tesseract'

# Set the path to the Tesseract data directory
os.environ['TESSDATA_PREFIX'] = '/usr/share/tesseract-ocr/4.00/tessdata/'

# Load the image
image_path = '/content/Grocery-Receipt-1.jpg'
img = Image.open(image_path)

# Convert the image to RGB format
img = img.convert('RGB')

# Use pytesseract to extract text
extracted_text = pytesseract.image_to_string(img)

# Print the extracted text

"""### **Extract ITEMS from the bill**"""

import re

# Define a function to extract items from the text
def extract_items(text):
    # Define a regular expression pattern to match item lines
    pattern = r'^([A-Za-z\s\d\./]+?)\s+\$?\d+\.\d{2}$'

    # Find all matches of the pattern in the text
    matches = re.findall(pattern, text, flags=re.MULTILINE)

    # Exclude lines containing total, cash, and change
    filtered_matches = [match.strip() for match in matches if not any(word in match.lower() for word in ['total', 'cash', 'change'])]

    # Return the extracted items
    return filtered_matches



# Extract items from the text
instance2_items = extract_items(extracted_text)

import re

# Define a function to extract items and their prices from the text
def extract_items_with_prices(text):
    # Define a regular expression pattern to match item lines
    pattern = r'^([A-Za-z\s\d\./]+?)\s+(\$?\d+\.\d{2})$'

    # Find all matches of the pattern in the text
    matches = re.findall(pattern, text, flags=re.MULTILINE)

    # Exclude lines containing total, cash, and change
    filtered_matches = [(item.strip(), price) for item, price in matches if not any(word in item.lower() for word in ['total', 'cash', 'change'])]

    # Return the extracted items and prices
    return filtered_matches

# Extract items and their prices from the text
extracted_items_with_prices = extract_items_with_prices(extracted_text)

"""### **Get TOTAL**"""

!pip install pytesseract
!apt-get install tesseract-ocr

import pytesseract

# Set the path to the Tesseract executable
pytesseract.pytesseract.tesseract_cmd = '/opt/homebrew/bin/tesseract'
##FINAL WORKINGGG FOR BOTH ##
import pytesseract
from PIL import Image
import os
import re

# Set the path to the Tesseract executable
pytesseract.pytesseract.tesseract_cmd = '/usr/bin/tesseract'

# Set the path to the Tesseract data directory
os.environ['TESSDATA_PREFIX'] = '/usr/share/tesseract-ocr/4.00/tessdata/'

# Load the image
image_path = '/content/Grocery-Receipt-1.jpg'
img = Image.open(image_path)

# Use pytesseract to extract text
extracted_text = pytesseract.image_to_string(img)

# Define a regular expression pattern to find 'Total' with associated number
pattern = r'(?:Total|total|TOTAL)\s*:\s*(\d+\.\d{2})'

# Find all matches of the pattern in the extracted text
matches = re.findall(pattern, extracted_text)

# If we found at least one total using the first approach
if matches:
    # Convert matches to float
    totals_from_first_approach = [float(match) for match in matches]

    # Get the maximum total value
    max_total_from_first_approach = max(totals_from_first_approach)
else:
    max_total_from_first_approach = None

# Initialize variable to hold the maximum total amount
max_total_amount = float('-inf')  # Set to negative infinity

# Split the extracted text into lines
lines = extracted_text.split('\n')

# Iterate over each line
for line in lines:
    # Check if the word "Total" is present in the line (case insensitive)
    if re.search(r'(?:Total|total|TOTAL)', line) or 'ROUNDED TOTAL' in line:
        # Extract numerical values from the line
        numbers = re.findall(r'[-+]?\d*\.\d+|\d+', line)

        # Convert the numerical values to float and find the maximum value
        total_amounts = [float(num.replace(',', '')) for num in numbers]
        if total_amounts:
            max_total_amount = max(max_total_amount, max(total_amounts))

# Compare the maximum totals from both approaches and print the maximum total
if max_total_from_first_approach is not None and max_total_amount != float('-inf'):
    max_total = max(max_total_from_first_approach, max_total_amount)
elif max_total_from_first_approach is not None:
    max_total = max_total_from_first_approach
elif max_total_amount != float('-inf'):
    max_total = max_total_amount
else:
    max_total = None

"""### **TRAIN**"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

# Sample data: items and their corresponding categories
# Extended sample data: items and their corresponding categories
items = [
    ("Instant Coffee Gold", "Groceries"),
    ("Rice Crackers Salt", "Groceries"),
    ("Plain Margarine", "Groceries"),
    ("Free Range Eggs", "Groceries"),
    ("Assorted Muesli", "Groceries"),
    ("Cookies", "Groceries"),
    ("Macaroni", "Groceries"),
    ("Buttermilk Dessert", "Groceries"),
    ("Wrapping Paper", "Personal Care"),
    ("Garden Gloves", "Personal Care"),
    ("Shampoo", "Personal Care"),
    ("Toothpaste", "Personal Care"),
    ("Body Lotion", "Personal Care"),
    ("Hand Soap", "Personal Care"),
    ("Hairbrush", "Personal Care"),
    ("Deodorant", "Personal Care"),
    ("Fruit Juice", "Groceries"),
    ("Cereal Bars", "Groceries"),
    ("Frozen Pizza", "Groceries"),
    ("Canned Soup", "Groceries"),
    ("Bread", "Groceries"),
    ("Pasta Sauce", "Groceries"),
    ("Frozen Vegetables", "Groceries"),
    ("Dish Soap", "Household Supplies"),
    ("Paper Towels", "Household Supplies"),
    ("Laundry Detergent", "Household Supplies"),
    ("Trash Bags", "Household Supplies"),
    ("Cleaning Spray", "Household Supplies"),
    ("Sponges", "Household Supplies"),
    ("Air Freshener", "Household Supplies"),
    ("Dishwasher Pods", "Household Supplies"),
    ("Batteries", "Household Supplies"),
    ("Light Bulbs", "Household Supplies"),
    ("Bandages", "Healthcare"),
    ("Cold Medicine", "Healthcare"),
    ("Vitamins", "Healthcare"),
    ("First Aid Kit", "Healthcare"),
    ("Thermometer", "Healthcare"),
    ("Sunscreen", "Healthcare"),
    ("Contact Solution", "Healthcare"),
    ("Allergy Medication", "Healthcare"),
    ("Prescription Glasses", "Healthcare"),
    ("Fitness Equipment", "Healthcare"),
    ("Movie Tickets", "Entertainment"),
    ("Concert Tickets", "Entertainment"),
    ("Restaurant Meals", "Entertainment"),
    ("Video Games", "Entertainment"),
    ("Books", "Entertainment"),
    ("Magazines", "Entertainment"),
    ("Streaming Subscription", "Entertainment"),
    ("Board Games", "Entertainment"),
    ("Sports Equipment", "Entertainment"),
    ("Art Supplies", "Entertainment"),
    ("Haircut", "Personal Care"),
    ("Manicure", "Personal Care"),
    ("Massage", "Personal Care"),
    ("Spa Day", "Personal Care"),
    ("Fitness Class", "Personal Care"),
    ("Yoga Mat", "Personal Care"),
    ("Gym Membership", "Personal Care"),
    ("Dental Checkup", "Healthcare"),
    ("Eye Exam", "Healthcare"),
    ("Chiropractic Appointment", "Healthcare"),
    ("Physical Therapy", "Healthcare"),
    ("Annual Physical", "Healthcare"),
    ("Medical Test", "Healthcare"),
    ("Doctor Consultation", "Healthcare"),
    ("Dentist Appointment", "Healthcare"),
    ("Optometrist Visit", "Healthcare"),
    ("Veterinary Appointment", "Healthcare"),
    ("Educational Books", "Education"),
    ("Online Courses", "Education"),
    ("Workshops", "Education"),
    ("School Supplies", "Education"),
    ("Tuition Fees", "Education"),
    ("Educational Software", "Education"),
    ("Educational Subscriptions", "Education"),
    ("Educational Toys", "Education"),
    ("Textbooks", "Education"),
    ("Student Loans", "Debts/Loans"),
    ("Credit Card Payment", "Debts/Loans"),
    ("Car Loan Payment", "Debts/Loans"),
    ("Mortgage Payment", "Debts/Loans"),
    ("Personal Loan Payment", "Debts/Loans"),
    ("Investment Contribution", "Savings/Investments"),
    ("Retirement Account Contribution", "Savings/Investments"),
    ("Savings Deposit", "Savings/Investments"),
    ("Stock Purchase", "Savings/Investments"),
    ("Mutual Fund Investment", "Savings/Investments"),
    ("IRA Contribution", "Savings/Investments"),
    ("401(k) Contribution", "Savings/Investments"),
    ("Emergency Fund", "Savings/Investments"),
    ("Vacation Fund", "Savings/Investments"),
    ("College Fund", "Savings/Investments"),
    ("Charitable Donation", "Miscellaneous"),
    ("Gift Purchase", "Miscellaneous"),
    ("Pet Supplies", "Miscellaneous"),
    ("Home Decor", "Miscellaneous"),
    ("Holiday Decorations", "Miscellaneous"),
    ("Craft Supplies", "Miscellaneous"),
    ("Special Occasion Expense", "Miscellaneous"),
    ("Unexpected Purchase", "Miscellaneous"),
      ("Instant Coffee Gold", "Groceries"),
    ("Rice Crackers Salt", "Groceries"),
    ("Plain Margarine", "Groceries"),
    ("Free Range Eggs", "Groceries"),
    ("Assorted Muesli", "Groceries"),
    ("Cookies", "Groceries"),
    ("Macaroni", "Groceries"),
    ("Buttermilk Dessert", "Groceries"),
    ("Wrapping Paper", "Personal Care"),
    ("Garden Gloves", "Personal Care"),
    ("Shampoo", "Personal Care"),
    ("Toothpaste", "Personal Care"),
    ("Body Lotion", "Personal Care"),
    ("Hand Soap", "Personal Care"),
    ("Hairbrush", "Personal Care"),
    ("Deodorant", "Personal Care"),
    ("Fruit Juice", "Groceries"),
    ("Cereal Bars", "Groceries"),
    ("Frozen Pizza", "Groceries"),
    ("Canned Soup", "Groceries"),
    ("Bread", "Groceries"),
    ("Pasta Sauce", "Groceries"),
    ("Frozen Vegetables", "Groceries"),
    ("Dish Soap", "Household Supplies"),
    ("Paper Towels", "Household Supplies"),
    ("Laundry Detergent", "Household Supplies"),
    ("Trash Bags", "Household Supplies"),
    ("Cleaning Spray", "Household Supplies"),
    ("Sponges", "Household Supplies"),
    ("Air Freshener", "Household Supplies"),
    ("Dishwasher Pods", "Household Supplies"),
    ("Batteries", "Household Supplies"),
    ("Light Bulbs", "Household Supplies"),
    ("Bandages", "Healthcare"),
    ("Cold Medicine", "Healthcare"),
    ("Vitamins", "Healthcare"),
    ("First Aid Kit", "Healthcare"),
    ("Thermometer", "Healthcare"),
    ("Sunscreen", "Healthcare"),
    ("Contact Solution", "Healthcare"),
    ("Allergy Medication", "Healthcare"),
    ("Prescription Glasses", "Healthcare"),
    ("Fitness Equipment", "Healthcare"),
    ("Movie Tickets", "Entertainment"),
    ("Concert Tickets", "Entertainment"),
    ("Restaurant Meals", "Entertainment"),
    ("Video Games", "Entertainment"),
    ("Books", "Entertainment"),
    ("Magazines", "Entertainment"),
    ("Streaming Subscription", "Entertainment"),
    ("Board Games", "Entertainment"),
    ("Sports Equipment", "Entertainment"),
    ("Art Supplies", "Entertainment"),
    ("Haircut", "Personal Care"),
    ("Manicure", "Personal Care"),
    ("Massage", "Personal Care"),
    ("Spa Day", "Personal Care"),
    ("Fitness Class", "Personal Care"),
    ("Yoga Mat", "Personal Care"),
    ("Gym Membership", "Personal Care"),
    ("Dental Checkup", "Healthcare"),
    ("Eye Exam", "Healthcare"),
    ("Chiropractic Appointment", "Healthcare"),
    ("Physical Therapy", "Healthcare"),
    ("Annual Physical", "Healthcare"),
    ("Medical Test", "Healthcare"),
    ("Doctor Consultation", "Healthcare"),
    ("Dentist Appointment", "Healthcare"),
    ("Optometrist Visit", "Healthcare"),
    ("Veterinary Appointment", "Healthcare"),
    ("Educational Books", "Education"),
    ("Online Courses", "Education"),
    ("Workshops", "Education"),
    ("School Supplies", "Education"),
    ("Tuition Fees", "Education"),
    ("Educational Software", "Education"),
    ("Educational Subscriptions", "Education"),
    ("Educational Toys", "Education"),
    ("Textbooks", "Education"),
    ("Student Loans", "Debts/Loans"),
    ("Credit Card Payment", "Debts/Loans"),
    ("Car Loan Payment", "Debts/Loans"),
    ("Mortgage Payment", "Debts/Loans"),
    ("Personal Loan Payment", "Debts/Loans"),
    ("Investment Contribution", "Savings/Investments"),
    ("Retirement Account Contribution", "Savings/Investments"),
    ("Savings Deposit", "Savings/Investments"),
    ("Stock Purchase", "Savings/Investments"),
    ("Mutual Fund Investment", "Savings/Investments"),
    ("IRA Contribution", "Savings/Investments"),
    ("401(k) Contribution", "Savings/Investments"),
    ("Emergency Fund", "Savings/Investments"),
    ("Vacation Fund", "Savings/Investments"),
    ("College Fund", "Savings/Investments"),
    ("Charitable Donation", "Miscellaneous"),
    ("Gift Purchase", "Miscellaneous"),
    ("Pet Supplies", "Miscellaneous"),
    ("Home Decor", "Miscellaneous"),
    ("Holiday Decorations", "Miscellaneous"),
    ("Craft Supplies", "Miscellaneous"),
    ("Special Occasion Expense", "Miscellaneous"),
    ("Unexpected Purchase", "Miscellaneous"),
    ("Kitchen Utensils", "Household Supplies"),
    ("Cookware", "Household Supplies"),
    ("Bed Linens", "Household Supplies"),
    ("Towels", "Household Supplies"),
    ("Furniture", "Household Supplies"),
    ("Electronics", "Household Supplies"),
    ("Home Appliances", "Household Supplies"),
    ("Outdoor Gear", "Household Supplies"),
    ("Gardening Tools", "Household Supplies"),
    ("Office Supplies", "Household Supplies"),
    ("Baby Supplies", "Household Supplies"),
    ("Party Supplies", "Household Supplies"),
    ("Stationery", "Household Supplies"),
    ("Craft Materials", "Household Supplies"),
    ("Pet Food", "Household Supplies"),
    ("Pet Accessories", "Household Supplies"),
    ("Pet Grooming", "Household Supplies"),
    ("Pet Healthcare", "Household Supplies"),
    ("Pet Toys", "Household Supplies"),
    ("Pet Beds", "Household Supplies"),
    ("Pet Cleaning", "Household Supplies"),
    ("Pet Training", "Household Supplies"),
    ("Pet Travel", "Household Supplies"),
    ("Pet Safety", "Household Supplies"),
    ("Pet Identification", "Household Supplies"),
    ("Pet Hygiene", "Household Supplies"),
    ("Pet Shelter", "Household Supplies"),
    ("Pet Breeding", "Household Supplies"),
    ("Pet Adoption", "Household Supplies"),
    ("Pet Care Services", "Household Supplies"),
    ("Pet Fencing", "Household Supplies"),
    ("Pet Containment", "Household Supplies"),
    ("Pet Enclosures", "Household Supplies"),
    ("Pet Habitats", "Household Supplies"),
    ("Pet Training Aids", "Household Supplies"),
    ("Pet Training Treats", "Household Supplies"),
    ("Pet Training Toys", "Household Supplies"),
    ("Pet Training Tools", "Household Supplies"),
    ("Instant Coffee Gold", "Groceries"),
    ("Rice Crackers Salt", "Groceries"),
    ("Plain Margarine", "Groceries"),
    ("Free Range Eggs", "Groceries"),
    ("Assorted Muesli", "Groceries"),
    ("Cookies", "Groceries"),
    ("Macaroni", "Groceries"),
    ("Buttermilk Dessert", "Groceries"),
    ("Wrapping Paper", "Personal Care"),
    ("Garden Gloves", "Personal Care"),
    ("Shampoo", "Personal Care"),
    ("Toothpaste", "Personal Care"),
    ("Body Lotion", "Personal Care"),
    ("Hand Soap", "Personal Care"),
    ("Hairbrush", "Personal Care"),
    ("Deodorant", "Personal Care"),
    ("Fruit Juice", "Groceries"),
    ("Cereal Bars", "Groceries"),
    ("Frozen Pizza", "Groceries"),
    ("Canned Soup", "Groceries"),
    ("Bread", "Groceries"),
    ("Pasta Sauce", "Groceries"),
    ("Frozen Vegetables", "Groceries"),
    ("Dish Soap", "Household Supplies"),
    ("Paper Towels", "Household Supplies"),
    ("Laundry Detergent", "Household Supplies"),
    ("Trash Bags", "Household Supplies"),
    ("Cleaning Spray", "Household Supplies"),
    ("Sponges", "Household Supplies"),
    ("Air Freshener", "Household Supplies"),
    ("Dishwasher Pods", "Household Supplies"),
    ("Batteries", "Household Supplies"),
    ("Light Bulbs", "Household Supplies"),
    ("Bandages", "Healthcare"),
    ("Cold Medicine", "Healthcare"),
    ("Vitamins", "Healthcare"),
    ("First Aid Kit", "Healthcare"),
    ("Thermometer", "Healthcare"),
    ("Sunscreen", "Healthcare"),
    ("Contact Solution", "Healthcare"),
    ("Allergy Medication", "Healthcare"),
    ("Prescription Glasses", "Healthcare"),
    ("Fitness Equipment", "Healthcare"),
    ("Movie Tickets", "Entertainment"),
    ("Concert Tickets", "Entertainment"),
    ("Restaurant Meals", "Entertainment"),
    ("Video Games", "Entertainment"),
    ("Books", "Entertainment"),
    ("Magazines", "Entertainment"),
    ("Streaming Subscription", "Entertainment"),
    ("Board Games", "Entertainment"),
    ("Sports Equipment", "Entertainment"),
    ("Art Supplies", "Entertainment"),
    ("Haircut", "Personal Care"),
    ("Manicure", "Personal Care"),
    ("Massage", "Personal Care"),
    ("Spa Day", "Personal Care"),
    ("Fitness Class", "Personal Care"),
    ("Yoga Mat", "Personal Care"),
    ("Gym Membership", "Personal Care"),
    ("Dental Checkup", "Healthcare"),
    ("Eye Exam", "Healthcare"),
    ("Chiropractic Appointment", "Healthcare"),
    ("Physical Therapy", "Healthcare"),
    ("Annual Physical", "Healthcare"),
    ("Medical Test", "Healthcare"),
    ("Doctor Consultation", "Healthcare"),
    ("Dentist Appointment", "Healthcare"),
    ("Optometrist Visit", "Healthcare"),
    ("Veterinary Appointment", "Healthcare"),
    ("Educational Books", "Education"),
    ("Online Courses", "Education"),
    ("Workshops", "Education"),
    ("School Supplies", "Education"),
    ("Tuition Fees", "Education"),
    ("Educational Software", "Education"),
    ("Educational Subscriptions", "Education"),
    ("Educational Toys", "Education"),
    ("Textbooks", "Education"),
    ("Student Loans", "Debts/Loans"),
    ("Credit Card Payment", "Debts/Loans"),
    ("Car Loan Payment", "Debts/Loans"),
    ("Mortgage Payment", "Debts/Loans"),
    ("Personal Loan Payment", "Debts/Loans"),
    ("Investment Contribution", "Savings/Investments"),
    ("Retirement Account Contribution", "Savings/Investments"),
    ("Savings Deposit", "Savings/Investments"),
    ("Stock Purchase", "Savings/Investments"),
    ("Mutual Fund Investment", "Savings/Investments"),
    ("IRA Contribution", "Savings/Investments"),
    ("401(k) Contribution", "Savings/Investments"),
    ("Emergency Fund", "Savings/Investments"),
    ("Vacation Fund", "Savings/Investments"),
    ("College Fund", "Savings/Investments"),
    ("Charitable Donation", "Miscellaneous"),
    ("Gift Purchase", "Miscellaneous"),
    ("Pet Supplies", "Miscellaneous"),
    ("Home Decor", "Miscellaneous"),
    ("Holiday Decorations", "Miscellaneous"),
    ("Craft Supplies", "Miscellaneous"),
    ("Special Occasion Expense", "Miscellaneous"),
    ("Unexpected Purchase", "Miscellaneous"),
    ("Salmon Fillet", "Groceries"),
    ("Spinach Leaves", "Groceries"),
    ("Chicken Breast", "Groceries"),
    ("Brown Rice", "Groceries"),
    ("Greek Yogurt", "Groceries"),
    ("Whole Wheat Bread", "Groceries"),
    ("Avocado", "Groceries"),
    ("Almonds", "Groceries"),
    ("Quinoa", "Groceries"),
    ("Sweet Potatoes", "Groceries"),
    ("Olive Oil", "Groceries"),
    ("Honey", "Groceries"),
    ("Cottage Cheese", "Groceries"),
    ("Blueberries", "Groceries"),
    ("Bananas", "Groceries"),
    ("Cucumber", "Groceries"),
    ("Tomatoes", "Groceries"),
    ("Eggs", "Groceries"),
    ("Milk", "Groceries"),
    ("Cheese", "Groceries"),
    ("Apples", "Groceries"),
    ("Carrots", "Groceries"),
    ("Broccoli", "Groceries"),
    ("Green Beans", "Groceries"),
    ("Oranges", "Groceries"),
    ("Strawberries", "Groceries"),
    ("Pineapple", "Groceries"),
    ("Peaches", "Groceries"),
    ("Watermelon", "Groceries"),
    ("Lettuce", "Groceries"),
    ("Bell Peppers", "Groceries"),
    ("Onions", "Groceries"),
    ("Garlic", "Groceries"),
    ("Ginger", "Groceries"),
    ("Basil", "Groceries"),
    ("Soy Milk", "Groceries"),
("Almond Butter", "Groceries"),
("Chia Seeds", "Groceries"),
("Coconut Oil", "Groceries"),
("Flaxseed", "Groceries"),
("Hummus", "Groceries"),
("Tofu", "Groceries"),
("Seitan", "Groceries"),
("Tempeh", "Groceries"),
("Nutritional Yeast", "Groceries"),
("Miso Paste", "Groceries"),
("Kombucha", "Groceries"),
("Sauerkraut", "Groceries"),
("Kimchi", "Groceries"),
("Tahini", "Groceries"),
("Agave Syrup", "Groceries"),
("Maple Syrup", "Groceries"),
("Quorn", "Groceries"),
("Plant-Based Milk", "Groceries"),
("Plant-Based Cheese", "Groceries"),
("Plant-Based Meat", "Groceries"),
("Frozen Berries", "Groceries"),
("Frozen Mango", "Groceries"),
("Frozen Pineapple", "Groceries"),
("Frozen Peas", "Groceries"),
("Frozen Corn", "Groceries"),
("Frozen Spinach", "Groceries"),
("Frozen Broccoli", "Groceries"),
("Frozen Cauliflower", "Groceries"),
("Frozen Brussels Sprouts", "Groceries"),
("Frozen Edamame", "Groceries"),
("Frozen Green Beans", "Groceries"),
("Frozen Mixed Vegetables", "Groceries"),
("Frozen Stir-Fry Vegetables", "Groceries"),
("Frozen Cherries", "Groceries"),
("Frozen Strawberries", "Groceries"),
("Frozen Blueberries", "Groceries"),
("Frozen Raspberries", "Groceries"),
("Frozen Blackberries", "Groceries"),
("Frozen Peaches", "Groceries"),
("Frozen Apricots", "Groceries"),
("Frozen Avocado", "Groceries"),
("Frozen Banana", "Groceries"),
("Frozen Papaya", "Groceries"),
("Frozen Coconut", "Groceries"),
("Frozen Acai", "Groceries"),
("Frozen Dragonfruit", "Groceries"),
("Frozen Kiwi", "Groceries"),
("Frozen Guava", "Groceries"),
("Frozen Lychee", "Groceries"),
("Frozen Passionfruit", "Groceries"),
("Frozen Pomegranate Seeds", "Groceries"),
("Frozen Watermelon", "Groceries"),
("Frozen Cantaloupe", "Groceries"),
("Frozen Honeydew", "Groceries"),
("Frozen Peaches and Cream", "Groceries"),
("Frozen Berry Medley", "Groceries"),
("Frozen Tropical Mix", "Groceries"),
("Frozen Superfood Blend", "Groceries"),
("Frozen Veggie Mix", "Groceries"),
("Frozen Smoothie Mix", "Groceries"),
("Frozen Protein Mix", "Groceries"),
("Frozen Breakfast Mix", "Groceries"),
("Frozen Dessert Mix", "Groceries"),
("Frozen Pizza Dough", "Groceries"),
("Frozen Waffles", "Groceries"),
("Frozen Pancakes", "Groceries"),
("Frozen French Toast", "Groceries"),
("Frozen Breakfast Sandwiches", "Groceries"),
("Frozen Burritos", "Groceries"),
("Frozen Empanadas", "Groceries"),
("Frozen Potstickers", "Groceries"),
("Frozen Dumplings", "Groceries"),
("Frozen Pierogies", "Groceries"),
("Frozen Taquitos", "Groceries"),
("Frozen Samosas", "Groceries"),
("Frozen Spring Rolls", "Groceries"),
("Frozen Appetizers", "Groceries"),
("Frozen Entrees", "Groceries"),
("Frozen Dinners", "Groceries"),
("Frozen Meals", "Groceries"),
("Frozen Treats", "Groceries"),
("Frozen Desserts", "Groceries"),
("Frozen Snacks", "Groceries"),
("Frozen Finger Foods", "Groceries"),
("Frozen Bites", "Groceries"),
("Frozen Delights", "Groceries"),
("Frozen Confections", "Groceries"),
("Frozen Delicacies", "Groceries"),
("Frozen Goodies", "Groceries"),
("Frozen Indulgences", "Groceries"),
("Frozen Pleasures", "Groceries"),
("Frozen Sweets", "Groceries"),
("Frozen Temptations", "Groceries"),
("Frozen Luxuries", "Groceries"),
("Frozen Decadence", "Groceries"),
("Frozen Joys", "Groceries"),
("Frozen Heaven", "Groceries"),
("Frozen Bliss", "Groceries"),
("Frozen Happiness", "Groceries"),
("Frozen Ecstasy", "Groceries"),
("Frozen Paradise", "Groceries"),
("Frozen Nirvana", "Groceries"),
("Frozen Euphoria", "Groceries"),
("Frozen Rapture", "Groceries"),
("Frozen Serenity", "Groceries"),
("Frozen Tranquility", "Groceries"),
("Frozen Contentment", "Groceries"),
("Frozen Peace", "Groceries"),
("Frozen Harmony", "Groceries"),
("Frozen Calm", "Groceries"),
("Frozen Quiet", "Groceries"),
("Frozen Stillness", "Groceries"),
("Frozen Rest", "Groceries"),
("Frozen Relaxation", "Groceries"),
("Frozen Repose", "Groceries"),
("Frozen Ease", "Groceries"),
("Frozen Comfort", "Groceries"),
("Frozen Relief", "Groceries"),
("Frozen Solace", "Groceries"),
("Frozen Freedom", "Groceries"),
("Frozen Liberty", "Groceries"),
("Frozen Release", "Groceries"),
("Frozen Deliverance", "Groceries"),
("Frozen Salvage", "Groceries"),
("Frozen Redemption", "Groceries"),
("Frozen Escape", "Groceries"),
("Frozen Rescue", "Groceries"),
("Frozen Sanctuary", "Groceries"),
("Frozen Safety", "Groceries"),
("Frozen Protection", "Groceries"),
("Frozen Security", "Groceries"),
("Frozen Shield", "Groceries"),
("Frozen Fortification", "Groceries"),
("Frozen Guard", "Groceries"),
("Frozen Bulwark", "Groceries"),
("Frozen Rampart", "Groceries"),
("Frozen Bastion", "Groceries"),
("Frozen Defense", "Groceries"),
("Frozen Safeguard", "Groceries"),
("Frozen Cover", "Groceries"),
("Frozen Barrier", "Groceries"),
("Frozen Wall", "Groceries"),
("Frozen Screen", "Groceries"),
("Frozen Veil", "Groceries"),
("Frozen Cloak", "Groceries"),
("Frozen Mantle", "Groceries"),
("Frozen Shell", "Groceries"),
("Frozen Casing", "Groceries"),
("Frozen Encasement", "Groceries"),
("Frozen Cocoon", "Groceries"),
("Frozen Wrap", "Groceries"),
("Frozen Binding", "Groceries"),
("Frozen Band", "Groceries"),
("Frozen Ring", "Groceries"),
("Frozen Loop", "Groceries"),
("Frozen Knot", "Groceries"),
("Frozen Tie", "Groceries"),
("Frozen Fastening", "Groceries"),
("Frozen Clasp", "Groceries"),
("Frozen Grip", "Groceries"),
("Frozen Grasp", "Groceries"),
("Frozen Hold", "Groceries"),
("Frozen Clutch", "Groceries"),
("Frozen Snatch", "Groceries"),
("Frozen Seize", "Groceries"),
("Frozen Capture", "Groceries"),
("Frozen Arrest", "Groceries"),
    ("Soy Milk", "Groceries"),
("Almond Butter", "Groceries"),
("Chia Seeds", "Groceries"),
("Coconut Oil", "Groceries"),
("Flaxseed", "Groceries"),
("Hummus", "Groceries"),
("Tofu", "Groceries"),
("Seitan", "Groceries"),
("Tempeh", "Groceries"),
("Nutritional Yeast", "Groceries"),
("Miso Paste", "Groceries"),
("Kombucha", "Groceries"),
("Sauerkraut", "Groceries"),
("Kimchi", "Groceries"),
("Tahini", "Groceries"),
("Agave Syrup", "Groceries"),
("Maple Syrup", "Groceries"),
("Quorn", "Groceries"),
("Plant-Based Milk", "Groceries"),
("Plant-Based Cheese", "Groceries"),
("Plant-Based Meat", "Groceries"),
("Frozen Berries", "Groceries"),
("Frozen Mango", "Groceries"),
("Frozen Pineapple", "Groceries"),
("Frozen Peas", "Groceries"),
("Frozen Corn", "Groceries"),
("Frozen Spinach", "Groceries"),
("Frozen Broccoli", "Groceries"),
("Frozen Cauliflower", "Groceries"),
("Frozen Brussels Sprouts", "Groceries"),
("Frozen Edamame", "Groceries"),
("Frozen Green Beans", "Groceries"),
("Frozen Mixed Vegetables", "Groceries"),
("Frozen Stir-Fry Vegetables", "Groceries"),
("Frozen Cherries", "Groceries"),
("Frozen Strawberries", "Groceries"),
("Frozen Blueberries", "Groceries"),
("Frozen Raspberries", "Groceries"),
("Frozen Blackberries", "Groceries"),
("Frozen Peaches", "Groceries"),
("Frozen Apricots", "Groceries"),
("Frozen Avocado", "Groceries"),
("Frozen Banana", "Groceries"),
("Frozen Papaya", "Groceries"),
("Frozen Coconut", "Groceries"),
("Frozen Acai", "Groceries"),
("Frozen Dragonfruit", "Groceries"),
("Frozen Kiwi", "Groceries"),
("Frozen Guava", "Groceries"),
("Frozen Lychee", "Groceries"),
("Frozen Passionfruit", "Groceries"),
("Frozen Pomegranate Seeds", "Groceries"),
("Frozen Watermelon", "Groceries"),
("Frozen Cantaloupe", "Groceries"),
("Frozen Honeydew", "Groceries"),
("Frozen Peaches and Cream", "Groceries"),
("Frozen Berry Medley", "Groceries"),
("Frozen Tropical Mix", "Groceries"),
("Frozen Superfood Blend", "Groceries"),
("Frozen Veggie Mix", "Groceries"),
("Frozen Smoothie Mix", "Groceries"),
("Frozen Protein Mix", "Groceries"),
("Frozen Breakfast Mix", "Groceries"),
("Frozen Dessert Mix", "Groceries"),
("Frozen Pizza Dough", "Groceries"),
("Frozen Waffles", "Groceries"),
("Frozen Pancakes", "Groceries"),
("Frozen French Toast", "Groceries"),
("Frozen Breakfast Sandwiches", "Groceries"),
("Frozen Burritos", "Groceries"),
("Frozen Empanadas", "Groceries"),
("Frozen Potstickers", "Groceries"),
("Frozen Dumplings", "Groceries"),
("Frozen Pierogies", "Groceries"),
("Frozen Taquitos", "Groceries"),
("Frozen Samosas", "Groceries"),
("Frozen Spring Rolls", "Groceries"),
("Frozen Appetizers", "Groceries"),
("Frozen Entrees", "Groceries"),
("Frozen Dinners", "Groceries"),
("Frozen Meals", "Groceries"),
("Frozen Treats", "Groceries"),
("Frozen Desserts", "Groceries"),
("Frozen Snacks", "Groceries"),
("Frozen Finger Foods", "Groceries"),
("Frozen Bites", "Groceries"),
("Frozen Delights", "Groceries"),
("Frozen Confections", "Groceries"),
("Frozen Delicacies", "Groceries"),
("Frozen Goodies", "Groceries"),
("Frozen Indulgences", "Groceries"),
("Frozen Pleasures", "Groceries"),
("Frozen Sweets", "Groceries"),
("Frozen Temptations", "Groceries"),
("Frozen Luxuries", "Groceries"),
("Frozen Decadence", "Groceries"),
("Frozen Joys", "Groceries"),
("Frozen Heaven", "Groceries"),
("Frozen Bliss", "Groceries"),
("Frozen Happiness", "Groceries"),
("Frozen Ecstasy", "Groceries"),
("Frozen Paradise", "Groceries"),
("Frozen Nirvana", "Groceries"),
("Frozen Euphoria", "Groceries"),
("Frozen Rapture", "Groceries"),
("Frozen Serenity", "Groceries"),
("Frozen Tranquility", "Groceries"),
("Frozen Contentment", "Groceries"),
("Frozen Peace", "Groceries"),
("Frozen Harmony", "Groceries"),
("Frozen Calm", "Groceries"),
("Frozen Quiet", "Groceries"),
("Frozen Stillness", "Groceries"),
("Frozen Rest", "Groceries"),
("Frozen Relaxation", "Groceries"),
("Frozen Repose", "Groceries"),
("Frozen Ease", "Groceries"),
("Frozen Comfort", "Groceries"),
("Frozen Relief", "Groceries"),
("Frozen Solace", "Groceries"),
("Frozen Freedom", "Groceries"),
("Frozen Liberty", "Groceries"),
("Frozen Release", "Groceries"),
("Frozen Deliverance", "Groceries"),
("Frozen Salvage", "Groceries"),
("Frozen Redemption", "Groceries"),
("Frozen Escape", "Groceries"),
("Frozen Rescue", "Groceries"),
("Frozen Sanctuary", "Groceries"),
("Frozen Safety", "Groceries"),
("Frozen Protection", "Groceries"),
("Frozen Security", "Groceries"),
("Frozen Shield", "Groceries"),
("Frozen Fortification", "Groceries"),
("Frozen Guard", "Groceries"),
("Frozen Bulwark", "Groceries"),
("Frozen Rampart", "Groceries"),
("Frozen Bastion", "Groceries"),
("Frozen Defense", "Groceries"),
("Frozen Safeguard", "Groceries"),
("Frozen Cover", "Groceries"),
("Frozen Barrier", "Groceries"),
("Frozen Wall", "Groceries"),
("Frozen Screen", "Groceries"),
("Frozen Veil", "Groceries"),
("Frozen Cloak", "Groceries"),
("Frozen Mantle", "Groceries"),
("Frozen Shell", "Groceries"),
("Frozen Casing", "Groceries"),
("Frozen Encasement", "Groceries"),
("Frozen Cocoon", "Groceries"),
("Frozen Wrap", "Groceries"),
("Frozen Binding", "Groceries"),
("Frozen Band", "Groceries"),
("Frozen Ring", "Groceries"),
("Frozen Loop", "Groceries"),
("Frozen Knot", "Groceries"),
("Frozen Tie", "Groceries"),
("Frozen Fastening", "Groceries"),
("Frozen Clasp", "Groceries"),
("Frozen Grip", "Groceries"),
("Frozen Grasp", "Groceries"),
("Frozen Hold", "Groceries"),
    ("Alo Tikki", "Food"),
    ("Chicken Tikka Masala", "Food"),
    ("Beef Stroganoff", "Food"),
    ("Pad Thai", "Food"),
    ("Sushi Rolls", "Food"),
    ("Margherita Pizza", "Food"),
    ("Hamburger", "Food"),
    ("Fish and Chips", "Food"),
    ("Caesar Salad", "Food"),
    ("Chicken Alfredo", "Food"),
    ("Tacos", "Food"),
    ("Lasagna", "Food"),
    ("Beef Bourguignon", "Food"),
    ("Grilled Salmon", "Food"),
    ("Vegetable Stir-Fry", "Food"),
    ("Butter Chicken", "Food"),
    ("Pasta Primavera", "Food"),
    ("Chicken Parmesan", "Food"),
    ("Beef Wellington", "Food"),
    ("Shrimp Scampi", "Food"),
    ("Eggplant Parmesan", "Food"),
    ("Fettuccine Alfredo", "Food"),
    ("Steak Frites", "Food"),
    ("Chicken Satay", "Food"),
    ("Ratatouille", "Food"),
    ("Vegetable Curry", "Food"),
    ("Beef Tacos", "Food"),
    ("Pad See Ew", "Food"),
    ("Biryani", "Food"),
    ("Paneer Tikka", "Food"),
    ("Tom Yum Soup", "Food"),
    ("Pho", "Food")
]

# Split data into features (item names) and labels (categories)
X = [item[0] for item in items]
y = [item[1] for item in items]

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a pipeline for text classification
text_clf = Pipeline([
    ('tfidf', TfidfVectorizer()),  # Convert item names into TF-IDF vectors
    ('clf', SVC(kernel='linear'))  # SVM classifier with linear kernel
])

# Train the classifier
text_clf.fit(X_train, y_train)

# Evaluate the classifier
y_pred = text_clf.predict(X_test)

"""### **TEST**"""

predicted_categories = text_clf.predict(instance2_items)

# Print the predicted categories for the extracted items
print("\nPredicted categories for the extracted items:")

"""### [Category With Price](https://)"""

import re

# Define a function to extract items and their prices from the text
def extract_items_with_prices(text):
    # Define a regular expression pattern to match item lines
    pattern = r'^([A-Za-z\s\d\./]+?)\s+(\$?\d+\.\d{2})$'

    # Find all matches of the pattern in the text
    matches = re.findall(pattern, text, flags=re.MULTILINE)

    # Exclude lines containing total, cash, and change
    filtered_matches = [(item.strip(), float(price)) for item, price in matches if not any(word in item.lower() for word in ['total', 'cash', 'change'])]

    # Return the extracted items and prices
    return filtered_matches

# Define a function to group items by category
def group_items_by_category(items_with_prices, predicted_categories):
    # Group items by category
    grouped_items = {}
    for (item, price), category in zip(items_with_prices, predicted_categories):
        if category not in grouped_items:
            grouped_items[category] = []
        grouped_items[category].append((item, price))

    return grouped_items

# Extract items and their prices from the text
extracted_items_with_prices = extract_items_with_prices(extracted_text)

# Assuming you have predicted_categories available from a previous step
predicted_categories = text_clf.predict(instance2_items)

# Group items by category
grouped_items = group_items_by_category(extracted_items_with_prices, predicted_categories)

# Calculate the total sum for each category
category_sums = {}
total_sum_all_categories = 0
for category, items in grouped_items.items():
    total_sum = sum(price for _, price in items)
    category_sums[category] = total_sum
    total_sum_all_categories += total_sum

# Calculate the total bill amount
total_bill_amount = sum(price for _, price in extracted_items_with_prices)

# Adjust the sum of each category proportionally to ensure it matches the total bill amount
for category, total_sum in category_sums.items():
    category_sums[category] = total_sum * (total_bill_amount / total_sum_all_categories)

# Print the total sum for each category